#!/usr/bin/env python3
"""Bricks database tool — the single door to a workspace's bricks.db.

Every read and write to workspace data goes through this script: skills and
agents never touch the database any other way (no raw sqlite3, no hand-written
SQL). Tables and columns are DYNAMIC, Clay-style: `add` creates the table on
first use, `add`/`modify` create missing columns on the fly. `_id` is the
reserved technical column (INTEGER PRIMARY KEY), generated by SQLite, never
set by callers. Mutations are all-or-nothing.

Database resolution: `--db <path>` explicit, otherwise the current workspace's
bricks.db (from ./bricks/config.json, override root with --root).

CLI (JSON on stdout; on error JSON on stderr + exit 1):
    python3 db.py [--db PATH] tables
    python3 db.py [--db PATH] schema  <table>
    python3 db.py [--db PATH] select  <table> [--where SQL] [--cols a,b] [--limit N] [--offset N]
    python3 db.py [--db PATH] add     <table> --rows '[{"name":"Acme"}]' [--key domain]
                                      # insert rows: JSON list of objects (or '-' = stdin)
    python3 db.py [--db PATH] modify  <table> --updates '[{"_id":3,"score":"A"}]'
    python3 db.py [--db PATH] remove  <table> --ids '[3,7]'
    python3 db.py [--db PATH] import-csv <table> <file.csv> [--key domain]

Pass '-' to --rows / --updates / --ids to read the JSON payload from stdin.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sqlite3
import sys

DEFAULT_SELECT_LIMIT = 50
ID = "_id"
IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class DbError(ValueError):
    """Raised on any invalid operation. The database is never modified."""


def resolve(db: str | None = None, root: str = "bricks") -> str:
    """Return the bricks.db path: explicit --db, or the current workspace's."""
    if db:
        return db
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import workspace
    try:
        return workspace.current_db(root)
    except workspace.WorkspaceError as exc:
        raise DbError(str(exc)) from None


def connect(path: str, create: bool = False) -> sqlite3.Connection:
    if not create and not os.path.isfile(path):
        raise DbError(f"database not found: {path} — run workspace.py new first")
    conn = sqlite3.connect(path)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=5000")
    conn.row_factory = sqlite3.Row
    return conn


def init(path: str) -> dict:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    connect(path, create=True).close()
    return {"ok": True, "action": "init", "db": os.path.abspath(path)}


# --------------------------------------------------------------------------
# Internals
# --------------------------------------------------------------------------

def _check_ident(name, what: str) -> str:
    if not isinstance(name, str) or not IDENT_RE.match(name):
        raise DbError(f"invalid {what} {name!r}: letters, digits and _ only")
    if what == "table name" and name.startswith("_"):
        raise DbError(f"invalid table name {name!r}: must not start with _")
    return name


def _q(name: str) -> str:
    return f'"{name}"'


def _check_where(where: str | None) -> str | None:
    if where is None:
        return None
    if not isinstance(where, str) or not where.strip() or ";" in where:
        raise DbError("--where must be a single non-empty SQL condition (no ';')")
    return where.strip()


def _cell(value):
    """Normalize a JSON/Python value into a storable cell."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None or isinstance(value, (int, float, str)):
        return value
    return json.dumps(value, ensure_ascii=False)


def _check_objects(items, name: str) -> None:
    if not isinstance(items, list) or not items or not all(isinstance(i, dict) for i in items):
        raise DbError(f"{name} must be a non-empty JSON list of objects")
    for obj in items:
        for key in obj:
            if key != ID:
                _check_ident(key, "column name")
                if key.startswith("_"):
                    raise DbError(f"column {key!r}: _-prefixed names are reserved")


def _table_exists(conn, table: str) -> bool:
    return conn.execute("SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
                        (table,)).fetchone() is not None


def _require_table(conn, table: str) -> None:
    _check_ident(table, "table name")
    if not _table_exists(conn, table):
        available = [r["name"] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name")]
        raise DbError(f"table {table!r} not found — existing tables: {available or 'none'}")


def columns(conn, table: str) -> list[str]:
    return [r["name"] for r in conn.execute(f"PRAGMA table_info({_q(table)})")]


def _ensure_columns(conn, table: str, wanted: list[str]) -> list[str]:
    existing = set(columns(conn, table))
    added = []
    for col in wanted:
        if col not in existing:
            try:
                conn.execute(f"ALTER TABLE {_q(table)} ADD COLUMN {_q(col)} TEXT")
                added.append(col)
            except sqlite3.OperationalError as exc:
                # parallel runner workers can race on the same new column
                if "duplicate column" not in str(exc).lower():
                    raise
            existing.add(col)
    return added


# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------

def tables(path: str) -> dict:
    conn = connect(path)
    try:
        names = [r["name"] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name")]
        entries = [{"table": n,
                    "rows": conn.execute(f"SELECT COUNT(*) AS c FROM {_q(n)}").fetchone()["c"],
                    "columns": columns(conn, n)} for n in names]
    finally:
        conn.close()
    return {"ok": True, "db": os.path.abspath(path), "tables": entries}


def schema(path: str, table: str) -> dict:
    conn = connect(path)
    try:
        _require_table(conn, table)
        cols = columns(conn, table)
        total = conn.execute(f"SELECT COUNT(*) AS c FROM {_q(table)}").fetchone()["c"]
    finally:
        conn.close()
    return {"ok": True, "table": table, "columns": cols, "rows": total}


def select(path: str, table: str, where: str | None = None, cols: str | None = None,
           limit: int | None = None, offset: int = 0) -> dict:
    conn = connect(path)
    try:
        _require_table(conn, table)
        where = _check_where(where)
        if cols:
            names = [_check_ident(c.strip(), "column name")
                     for c in cols.split(",") if c.strip()]
            unknown = [c for c in names if c not in columns(conn, table)]
            if unknown:
                raise DbError(f"unknown column(s) {unknown} in {table}")
            selection = ", ".join(_q(c) for c in names)
        else:
            selection = "*"
        query = f"SELECT {selection} FROM {_q(table)}"
        if where:
            query += f" WHERE {where}"
        effective_limit = DEFAULT_SELECT_LIMIT if limit is None else limit
        if effective_limit >= 0:
            query += f" LIMIT {int(effective_limit)} OFFSET {int(offset)}"
        try:
            rows = [dict(r) for r in conn.execute(query)]
        except sqlite3.Error as exc:
            raise DbError(f"query failed ({exc}) — query was: {query}") from None
        total = conn.execute(
            f"SELECT COUNT(*) AS c FROM {_q(table)}" + (f" WHERE {where}" if where else "")
        ).fetchone()["c"]
    finally:
        conn.close()
    return {"ok": True, "table": table, "returned": len(rows), "matching": total, "rows": rows}


def add(path: str, table: str, rows: list[dict], key: str | None = None) -> dict:
    _check_ident(table, "table name")
    _check_objects(rows, "rows")
    if any(ID in r for r in rows):
        raise DbError(f'"{ID}" is generated by the database — remove it from your rows')
    ordered_cols: list[str] = []
    for r in rows:
        for k in r:
            if k not in ordered_cols:
                ordered_cols.append(k)
    if key and key not in ordered_cols:
        raise DbError(f"--key {key!r} must be present in the rows being added")

    conn = connect(path)
    try:
        with conn:
            created = not _table_exists(conn, table)
            if created:
                cols_sql = ", ".join(f"{_q(c)} TEXT" for c in ordered_cols)
                conn.execute(f"CREATE TABLE {_q(table)} "
                             f"({_q(ID)} INTEGER PRIMARY KEY AUTOINCREMENT, {cols_sql})")
                new_columns = ordered_cols
            else:
                new_columns = _ensure_columns(conn, table, ordered_cols)
            skipped = 0
            if key:
                seen = {r["v"] for r in conn.execute(
                    f"SELECT {_q(key)} AS v FROM {_q(table)} WHERE {_q(key)} IS NOT NULL")}
                kept = []
                for r in rows:
                    value = _cell(r.get(key))
                    if value is not None and value in seen:
                        skipped += 1
                        continue
                    if value is not None:
                        seen.add(value)
                    kept.append(r)
                rows = kept
            for r in rows:
                cols = list(r.keys())
                conn.execute(
                    f"INSERT INTO {_q(table)} ({', '.join(_q(c) for c in cols)}) "
                    f"VALUES ({','.join('?' * len(cols))})",
                    [_cell(r[c]) for c in cols])
            total = conn.execute(f"SELECT COUNT(*) AS c FROM {_q(table)}").fetchone()["c"]
    finally:
        conn.close()
    return {"ok": True, "action": "add", "table": table, "created": created,
            "added": len(rows), "skippedDuplicates": skipped,
            "newColumns": new_columns, "rows": total}


def modify(path: str, table: str, updates: list[dict]) -> dict:
    _check_objects(updates, "updates")
    ids = []
    for u in updates:
        if ID not in u or len(u) < 2:
            raise DbError(f'every update object needs "{ID}" plus columns to set, got: {u}')
        try:
            ids.append(int(u[ID]))
        except (TypeError, ValueError):
            raise DbError(f"invalid {ID} {u[ID]!r}: must be an integer") from None
    wanted = []
    for u in updates:
        for k in u:
            if k != ID and k not in wanted:
                wanted.append(k)
    conn = connect(path)
    try:
        _require_table(conn, table)
        with conn:
            placeholders = ",".join("?" * len(ids))
            found = {r[ID] for r in conn.execute(
                f"SELECT {_q(ID)} FROM {_q(table)} WHERE {_q(ID)} IN ({placeholders})", ids)}
            missing = sorted(set(ids) - found)
            if missing:
                raise DbError(f"{ID}(s) not found in {table}: {missing} — nothing was modified")
            new_columns = _ensure_columns(conn, table, wanted)
            cells = 0
            for u, row_id in zip(updates, ids):
                cols = [k for k in u if k != ID]
                conn.execute(
                    f"UPDATE {_q(table)} SET {', '.join(f'{_q(c)}=?' for c in cols)} "
                    f"WHERE {_q(ID)}=?",
                    [_cell(u[c]) for c in cols] + [row_id])
                cells += len(cols)
    finally:
        conn.close()
    return {"ok": True, "action": "modify", "table": table,
            "updatedRows": len(set(ids)), "updatedCells": cells, "newColumns": new_columns}


def remove(path: str, table: str, ids: list) -> dict:
    if not isinstance(ids, list) or not ids:
        raise DbError("--ids must be a non-empty JSON list of _id values")
    try:
        int_ids = [int(i) for i in ids]
    except (TypeError, ValueError):
        raise DbError(f"--ids must contain integers, got: {ids}") from None
    conn = connect(path)
    try:
        _require_table(conn, table)
        with conn:
            placeholders = ",".join("?" * len(int_ids))
            cursor = conn.execute(
                f"DELETE FROM {_q(table)} WHERE {_q(ID)} IN ({placeholders})", int_ids)
            total = conn.execute(f"SELECT COUNT(*) AS c FROM {_q(table)}").fetchone()["c"]
    finally:
        conn.close()
    return {"ok": True, "action": "remove", "table": table,
            "removed": cursor.rowcount, "rows": total}


def import_csv(path: str, table: str, file: str, key: str | None = None) -> dict:
    if not os.path.isfile(file):
        raise DbError(f"file not found: {file}")
    with open(file, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            raise DbError(f"empty CSV (no header row): {file}")
        rows = []
        for raw in reader:
            row = {k: v for k, v in raw.items()
                   if k and k != ID and not k.startswith("_")}
            if any((v or "").strip() for v in row.values()):
                rows.append(row)
    if not rows:
        raise DbError(f"no data rows in {file}")
    result = add(path, table, rows, key=key)
    result.update({"action": "import-csv", "file": file})
    return result


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def _load_json(value: str, flag: str):
    if value == "-":
        value = sys.stdin.read()
    try:
        return json.loads(value)
    except json.JSONDecodeError as exc:
        raise DbError(f"{flag}: invalid JSON ({exc})") from None


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Single door to a Bricks workspace database (JSON in, JSON out).")
    parser.add_argument("--root", default="bricks")
    parser.add_argument("--db", default=None, help="explicit bricks.db path")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("tables")
    p = sub.add_parser("schema"); p.add_argument("table")
    p = sub.add_parser("select")
    p.add_argument("table")
    p.add_argument("--where", default=None)
    p.add_argument("--cols", default=None)
    p.add_argument("--limit", type=int, default=None, help="-1 = no limit")
    p.add_argument("--offset", type=int, default=0)
    p = sub.add_parser("add")
    p.add_argument("table")
    p.add_argument("--rows", required=True,
                   help="insert: JSON list of objects, or '-' to read from stdin")
    p.add_argument("--key", default=None, help="dedup column")
    p = sub.add_parser("modify")
    p.add_argument("table")
    p.add_argument("--updates", required=True, help='JSON list with "_id", or \'-\' for stdin')
    p = sub.add_parser("remove")
    p.add_argument("table")
    p.add_argument("--ids", required=True, help="JSON list of _id values, or '-' for stdin")
    p = sub.add_parser("import-csv")
    p.add_argument("table")
    p.add_argument("file")
    p.add_argument("--key", default=None)

    args = parser.parse_args(argv)
    try:
        path = resolve(args.db, args.root)
        if args.command == "tables":
            result = tables(path)
        elif args.command == "schema":
            result = schema(path, args.table)
        elif args.command == "select":
            result = select(path, args.table, args.where, args.cols, args.limit, args.offset)
        elif args.command == "add":
            result = add(path, args.table, _load_json(args.rows, "--rows"), args.key)
        elif args.command == "modify":
            result = modify(path, args.table, _load_json(args.updates, "--updates"))
        elif args.command == "remove":
            result = remove(path, args.table, _load_json(args.ids, "--ids"))
        else:
            result = import_csv(path, args.table, args.file, args.key)
    except DbError as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False),
              file=sys.stderr)
        return 1
    print(json.dumps(result, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
