#!/usr/bin/env python3
"""Bricks database tool — the single door to a workspace's bricks.db.

Every read and write to workspace data goes through this script. Skills and
agents NEVER touch the database any other way (no raw sqlite3, no ORM, no
hand-written SQL in the conversation). The front server imports this module,
so the UI and the skills share exactly the same code paths.

Design contract (see CONVENTIONS.md at the plugin root):
- One SQLite database per workspace: `<workspace>/bricks.db`, WAL mode, so
  several writers (subagents in parallel) can work safely.
- Tables and columns are DYNAMIC, Clay-style: `add` creates the table on
  first use, `add`/`modify` create missing columns on the fly (ALTER TABLE).
- `_id` is the reserved technical column (INTEGER PRIMARY KEY): generated by
  SQLite, never set by callers, never displayed by the front. Rows are
  addressed by `_id` — stable under concurrent inserts and deletes.
- An enrichment column `X` is paired with `X_status` using the shared
  vocabulary: pending | running | done | not_found | failed.
- Mutations are all-or-nothing: any validation error aborts the whole
  command before anything is written (exit code != 0 means "not modified").

Database resolution: `--db <path>` explicit, otherwise the current
workspace's bricks.db (from ./bricks/config.json, override root with --root).
`--db` / `--root` may be placed BEFORE or AFTER the subcommand — both
`db.py --db X add …` and `db.py add … --db X` work.

CLI (JSON on stdout; on error JSON on stderr + exit 1):
    python3 db.py init
    python3 db.py tables
    python3 db.py schema  <table>
    python3 db.py select  <table> [--where SQL] [--cols a,b] [--limit N] [--offset N] [--order SQL]
    python3 db.py count   <table> [--where SQL]
    python3 db.py claim   <table> <status_col> [--limit 25] [--cols a,b] [--where SQL] [--retry-failed]
    python3 db.py add     <table> --rows '[{"name": "Acme"}]'        [--key domain]
    python3 db.py modify  <table> --updates '[{"_id": 3, "score": "A"}]'
    python3 db.py modify  <table> --set website_status=running --where "website_status='pending'"
    python3 db.py remove  <table> --ids '[3, 7]'
    python3 db.py remove  <table> --where "status='disqualified'"
    python3 db.py drop-table <table> --confirm
    python3 db.py drop-column <table> <column>
    python3 db.py import-csv <table> <file.csv> [--key domain]

Pass '-' to --rows / --updates / --ids to read the JSON payload from stdin.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sqlite3
import sys

DB_FILENAME = "bricks.db"
ID_COLUMN = "_id"
DEFAULT_SELECT_LIMIT = 50

#: Table and column names: plain identifiers only — everything else is
#: quoted data, never SQL. This is what makes dynamic DDL injection-safe.
#: A leading _ is allowed so `_id` stays selectable; CREATING _-prefixed
#: columns is still rejected by the reserved-name checks.
IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


class DbError(ValueError):
    """Raised on any invalid operation. The database is never modified."""


# --------------------------------------------------------------------------
# Resolution & connection
# --------------------------------------------------------------------------

def resolve_db_path(root: str = "bricks", db: str | None = None) -> str:
    """Return the bricks.db path: explicit --db, or the current workspace's."""
    if db:
        return db
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    import workspace as ws
    status = ws.status(root)
    if not status.get("initialized"):
        raise DbError(
            f"Bricks not initialized at {os.path.abspath(root)} — "
            "run workspace.py init / new first"
        )
    current = status.get("current")
    if not current:
        raise DbError(
            "no current workspace — run workspace.py new <name> or switch <name>"
        )
    return os.path.join(current["path"], DB_FILENAME)


def connect(path: str, create: bool = False) -> sqlite3.Connection:
    if not create and not os.path.isfile(path):
        raise DbError(f"database not found: {path} — run `init` (or workspace.py new)")
    conn = sqlite3.connect(path)
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA busy_timeout=5000")
    conn.row_factory = sqlite3.Row
    return conn


# --------------------------------------------------------------------------
# Internals
# --------------------------------------------------------------------------

def _check_ident(name: str, what: str) -> str:
    if not isinstance(name, str) or not IDENT_RE.match(name):
        raise DbError(f"invalid {what} {name!r}: letters, digits and _ only")
    if what == "table name" and name.startswith("_"):
        raise DbError(f"invalid table name {name!r}: must not start with _")
    return name


def _q(name: str) -> str:
    return f'"{name}"'


def _check_where(where: str | None) -> str | None:
    if where is None:
        return None
    if not isinstance(where, str) or not where.strip():
        raise DbError("--where must be a non-empty SQL condition")
    if ";" in where:
        raise DbError("--where must be a single condition (no ';')")
    return where.strip()


def _cell(value):
    """Normalize a JSON/Python value into a storable cell."""
    if value is None or isinstance(value, (int, float, str)):
        if isinstance(value, bool):
            return "true" if value else "false"
        return value
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value, ensure_ascii=False)


def _check_objects(items, name: str) -> None:
    if not isinstance(items, list) or not items or not all(isinstance(i, dict) for i in items):
        raise DbError(f"{name} must be a non-empty JSON list of objects")


def _reject_reserved(objects: list[dict], what: str) -> None:
    for o in objects:
        for key in o:
            if key != ID_COLUMN and isinstance(key, str) and key.startswith("_"):
                raise DbError(
                    f"column {key!r}: names starting with _ are reserved for "
                    f"Bricks technical columns — remove it from your {what}"
                )
    if what == "rows" and any(ID_COLUMN in o for o in objects):
        raise DbError(
            f'"{ID_COLUMN}" is generated by the database — remove it from your rows'
        )


def _table_exists(conn: sqlite3.Connection, table: str) -> bool:
    row = conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", (table,)
    ).fetchone()
    return row is not None


def _require_table(conn: sqlite3.Connection, table: str) -> None:
    _check_ident(table, "table name")
    if not _table_exists(conn, table):
        available = [r["name"] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )]
        raise DbError(f"table {table!r} not found — existing tables: {available or 'none'}")


def _columns(conn: sqlite3.Connection, table: str) -> list[str]:
    return [r["name"] for r in conn.execute(f"PRAGMA table_info({_q(table)})")]


def _ensure_columns(conn: sqlite3.Connection, table: str, wanted: list[str]) -> list[str]:
    """ALTER TABLE ADD COLUMN for every column not yet in the table."""
    existing = set(_columns(conn, table))
    added = []
    for col in wanted:
        if col in existing:
            continue
        _check_ident(col, "column name")
        conn.execute(f"ALTER TABLE {_q(table)} ADD COLUMN {_q(col)} TEXT")
        existing.add(col)
        added.append(col)
    return added


def _ids_of(updates_or_ids, table: str) -> list[int]:
    """Coerce a list of ids (ints or numeric strings) to ints."""
    out = []
    for value in updates_or_ids:
        if isinstance(value, bool) or not isinstance(value, (int, str)):
            raise DbError(f"invalid {ID_COLUMN} {value!r} for {table}: must be an integer")
        try:
            out.append(int(value))
        except (TypeError, ValueError):
            raise DbError(f"invalid {ID_COLUMN} {value!r} for {table}: must be an integer") from None
    return out


def _require_ids_exist(conn: sqlite3.Connection, table: str, ids: list[int]) -> None:
    placeholders = ",".join("?" * len(ids))
    found = {r[ID_COLUMN] for r in conn.execute(
        f"SELECT {_q(ID_COLUMN)} FROM {_q(table)} WHERE {_q(ID_COLUMN)} IN ({placeholders})",
        ids,
    )}
    missing = sorted(set(ids) - found)
    if missing:
        raise DbError(f"{ID_COLUMN}(s) not found in {table}: {missing} — nothing was modified")


# --------------------------------------------------------------------------
# Commands
# --------------------------------------------------------------------------

def init(path: str) -> dict:
    existed = os.path.isfile(path)
    directory = os.path.dirname(os.path.abspath(path))
    os.makedirs(directory, exist_ok=True)
    conn = connect(path, create=True)
    conn.close()
    return {"ok": True, "action": "init", "db": os.path.abspath(path),
            "alreadyExisted": existed}


def tables(path: str) -> dict:
    conn = connect(path)
    try:
        names = [r["name"] for r in conn.execute(
            "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )]
        entries = [
            {"table": n,
             "rows": conn.execute(f"SELECT COUNT(*) AS c FROM {_q(n)}").fetchone()["c"],
             "columns": _columns(conn, n)}
            for n in names
        ]
    finally:
        conn.close()
    return {"ok": True, "db": os.path.abspath(path), "tables": entries}


def schema(path: str, table: str) -> dict:
    conn = connect(path)
    try:
        _require_table(conn, table)
        cols = _columns(conn, table)
        count = conn.execute(f"SELECT COUNT(*) AS c FROM {_q(table)}").fetchone()["c"]
    finally:
        conn.close()
    return {"ok": True, "table": table, "columns": cols, "rows": count}


def select(path: str, table: str, where: str | None = None, cols: str | None = None,
           limit: int | None = None, offset: int = 0, order: str | None = None) -> dict:
    conn = connect(path)
    try:
        _require_table(conn, table)
        where = _check_where(where)
        if cols:
            names = [_check_ident(c.strip(), "column name") for c in cols.split(",") if c.strip()]
            existing = set(_columns(conn, table))
            unknown = [c for c in names if c not in existing]
            if unknown:
                raise DbError(f"unknown column(s) {unknown} in {table} — columns: {sorted(existing)}")
            selection = ", ".join(_q(c) for c in names)
        else:
            selection = "*"
        query = f"SELECT {selection} FROM {_q(table)}"
        if where:
            query += f" WHERE {where}"
        if order:
            if ";" in order:
                raise DbError("--order must be a plain ORDER BY clause (no ';')")
            query += f" ORDER BY {order}"
        effective_limit = DEFAULT_SELECT_LIMIT if limit is None else limit
        if effective_limit >= 0:
            query += f" LIMIT {int(effective_limit)} OFFSET {int(offset)}"
        try:
            rows = [dict(r) for r in conn.execute(query)]
        except sqlite3.Error as exc:
            raise DbError(f"query failed ({exc}) — query was: {query}") from None
        total = conn.execute(
            f"SELECT COUNT(*) AS c FROM {_q(table)}" + (f" WHERE {where}" if where else "")
        ).fetchone()["c"]
    finally:
        conn.close()
    return {"ok": True, "table": table, "returned": len(rows), "matching": total,
            "limit": effective_limit, "rows": rows}


def count(path: str, table: str, where: str | None = None) -> dict:
    conn = connect(path)
    try:
        _require_table(conn, table)
        where = _check_where(where)
        query = f"SELECT COUNT(*) AS c FROM {_q(table)}" + (f" WHERE {where}" if where else "")
        try:
            total = conn.execute(query).fetchone()["c"]
        except sqlite3.Error as exc:
            raise DbError(f"query failed ({exc}) — query was: {query}") from None
    finally:
        conn.close()
    return {"ok": True, "table": table, "count": total}


def claim(path: str, table: str, status_col: str, limit: int = 25,
          cols: str | None = None, where: str | None = None,
          retry_failed: bool = False) -> dict:
    """Atomically select up to `limit` pending rows and mark them running.

    One command instead of the select-then-modify pair, inside a single
    BEGIN IMMEDIATE transaction: the write lock is taken BEFORE the select,
    so two parallel runs can never claim the same rows (the two-step
    pattern had that race). Rows whose row-level `status` is
    'disqualified' are never claimed (§5/§8); `--retry-failed` widens the
    scope to 'failed' rows on an explicit retry (iron rule 2).
    """
    _check_ident(status_col, "column name")
    if limit <= 0:
        raise DbError("--limit must be a positive integer")
    conn = connect(path)
    try:
        _require_table(conn, table)
        existing = _columns(conn, table)
        if status_col not in existing:
            raise DbError(f"column {status_col!r} not found in {table} — "
                          f"initialize it to 'pending' first (columns: {sorted(existing)})")
        if cols:
            names = [_check_ident(c.strip(), "column name") for c in cols.split(",") if c.strip()]
            unknown = [c for c in names if c not in existing]
            if unknown:
                raise DbError(f"unknown column(s) {unknown} in {table} — columns: {sorted(existing)}")
            if ID_COLUMN not in names:
                names.insert(0, ID_COLUMN)
            selection = ", ".join(_q(c) for c in names)
        else:
            selection = "*"
        statuses = "('pending','failed')" if retry_failed else "('pending')"
        cond = f"{_q(status_col)} IN {statuses}"
        if "status" in existing:
            cond += " AND (status IS NULL OR status!='disqualified')"
        extra = _check_where(where)
        if extra:
            cond += f" AND ({extra})"

        old_isolation = conn.isolation_level
        conn.isolation_level = None  # manual transaction: BEGIN IMMEDIATE
        try:
            conn.execute("BEGIN IMMEDIATE")
            try:
                ids = [r[ID_COLUMN] for r in conn.execute(
                    f"SELECT {_q(ID_COLUMN)} FROM {_q(table)} WHERE {cond} "
                    f"ORDER BY {_q(ID_COLUMN)} LIMIT ?", (int(limit),))]
            except sqlite3.Error as exc:
                raise DbError(f"claim failed ({exc}) — condition was: {cond}") from None
            rows = []
            if ids:
                placeholders = ",".join("?" * len(ids))
                conn.execute(
                    f"UPDATE {_q(table)} SET {_q(status_col)}='running' "
                    f"WHERE {_q(ID_COLUMN)} IN ({placeholders})", ids)
                rows = [dict(r) for r in conn.execute(
                    f"SELECT {selection} FROM {_q(table)} "
                    f"WHERE {_q(ID_COLUMN)} IN ({placeholders}) "
                    f"ORDER BY {_q(ID_COLUMN)}", ids)]
            conn.execute("COMMIT")
        except BaseException:
            conn.execute("ROLLBACK")
            raise
        finally:
            conn.isolation_level = old_isolation
    finally:
        conn.close()
    return {"ok": True, "action": "claim", "table": table,
            "statusCol": status_col, "claimed": len(rows), "rows": rows}


def add(path: str, table: str, rows: list[dict], key: str | None = None) -> dict:
    _check_ident(table, "table name")
    _check_objects(rows, "rows")
    _reject_reserved(rows, "rows")
    ordered_cols: list[str] = []
    for r in rows:
        for k in r:
            _check_ident(k, "column name")
            if k not in ordered_cols:
                ordered_cols.append(k)
    if key:
        _check_ident(key, "key column")
        if key not in ordered_cols:
            raise DbError(f"--key {key!r} must be present in the rows being added")

    conn = connect(path)
    try:
        with conn:
            created = not _table_exists(conn, table)
            if created:
                cols_sql = ", ".join(f"{_q(c)} TEXT" for c in ordered_cols)
                conn.execute(
                    f"CREATE TABLE {_q(table)} "
                    f"({_q(ID_COLUMN)} INTEGER PRIMARY KEY AUTOINCREMENT, {cols_sql})"
                )
                new_columns = ordered_cols
            else:
                new_columns = _ensure_columns(conn, table, ordered_cols)

            skipped = 0
            if key:
                seen = {
                    r["v"] for r in conn.execute(
                        f"SELECT {_q(key)} AS v FROM {_q(table)} WHERE {_q(key)} IS NOT NULL"
                    )
                }
                unique_rows = []
                for r in rows:
                    value = _cell(r.get(key))
                    if value is not None and value in seen:
                        skipped += 1
                        continue
                    if value is not None:
                        seen.add(value)
                    unique_rows.append(r)
                rows = unique_rows

            for r in rows:
                cols = list(r.keys())
                placeholders = ",".join("?" * len(cols))
                conn.execute(
                    f"INSERT INTO {_q(table)} ({', '.join(_q(c) for c in cols)}) "
                    f"VALUES ({placeholders})",
                    [_cell(r[c]) for c in cols],
                )
            total = conn.execute(f"SELECT COUNT(*) AS c FROM {_q(table)}").fetchone()["c"]
    finally:
        conn.close()
    return {"ok": True, "action": "add", "table": table, "created": created,
            "added": len(rows), "skippedDuplicates": skipped,
            "newColumns": new_columns, "rows": total}


def modify(path: str, table: str, updates: list[dict] | None = None,
           sets: dict | None = None, where: str | None = None) -> dict:
    conn = connect(path)
    try:
        _require_table(conn, table)
        if updates is not None:
            _check_objects(updates, "updates")
            _reject_reserved(updates, "updates")
            for u in updates:
                if ID_COLUMN not in u:
                    raise DbError(f'every update object needs a "{ID_COLUMN}" key, got: {u}')
                if len(u) < 2:
                    raise DbError(f"update for {ID_COLUMN}={u[ID_COLUMN]} has no columns to set")
            ids = _ids_of([u[ID_COLUMN] for u in updates], table)
            wanted = []
            for u in updates:
                for k in u:
                    if k != ID_COLUMN and k not in wanted:
                        _check_ident(k, "column name")
                        wanted.append(k)
            with conn:
                _require_ids_exist(conn, table, ids)
                new_columns = _ensure_columns(conn, table, wanted)
                updated_cells = 0
                for u, row_id in zip(updates, ids):
                    cols = [k for k in u if k != ID_COLUMN]
                    assignments = ", ".join(f"{_q(c)}=?" for c in cols)
                    conn.execute(
                        f"UPDATE {_q(table)} SET {assignments} WHERE {_q(ID_COLUMN)}=?",
                        [_cell(u[c]) for c in cols] + [row_id],
                    )
                    updated_cells += len(cols)
            return {"ok": True, "action": "modify", "table": table,
                    "updatedRows": len(set(ids)), "updatedCells": updated_cells,
                    "newColumns": new_columns}

        # bulk mode: --set col=value ... --where "..."
        if not sets:
            raise DbError("modify needs --updates, or --set with --where")
        where = _check_where(where)
        if not where:
            raise DbError("bulk --set requires --where (refusing to update every row blindly; "
                          "use --where 1=1 to really target all rows)")
        for k in sets:
            _check_ident(k, "column name")
            if k.startswith("_"):
                raise DbError(f"column {k!r} is reserved — technical columns cannot be set")
        with conn:
            new_columns = _ensure_columns(conn, table, list(sets.keys()))
            assignments = ", ".join(f"{_q(c)}=?" for c in sets)
            try:
                cursor = conn.execute(
                    f"UPDATE {_q(table)} SET {assignments} WHERE {where}",
                    [_cell(v) for v in sets.values()],
                )
            except sqlite3.Error as exc:
                raise DbError(f"update failed ({exc}) — where was: {where}") from None
            updated = cursor.rowcount
        return {"ok": True, "action": "modify", "table": table,
                "updatedRows": updated, "newColumns": new_columns, "where": where}
    finally:
        conn.close()


def remove(path: str, table: str, ids: list | None = None, where: str | None = None) -> dict:
    if (ids is None) == (where is None):
        raise DbError("remove needs exactly one of --ids or --where")
    conn = connect(path)
    try:
        _require_table(conn, table)
        with conn:
            if ids is not None:
                if not isinstance(ids, list) or not ids:
                    raise DbError("--ids must be a non-empty JSON list of _id values")
                int_ids = _ids_of(ids, table)
                _require_ids_exist(conn, table, int_ids)
                placeholders = ",".join("?" * len(int_ids))
                cursor = conn.execute(
                    f"DELETE FROM {_q(table)} WHERE {_q(ID_COLUMN)} IN ({placeholders})",
                    int_ids,
                )
            else:
                where = _check_where(where)
                try:
                    cursor = conn.execute(f"DELETE FROM {_q(table)} WHERE {where}")
                except sqlite3.Error as exc:
                    raise DbError(f"delete failed ({exc}) — where was: {where}") from None
            removed = cursor.rowcount
            total = conn.execute(f"SELECT COUNT(*) AS c FROM {_q(table)}").fetchone()["c"]
    finally:
        conn.close()
    return {"ok": True, "action": "remove", "table": table,
            "removed": removed, "rows": total}


def drop_table(path: str, table: str) -> dict:
    conn = connect(path)
    try:
        _require_table(conn, table)
        row_count = conn.execute(f"SELECT COUNT(*) AS c FROM {_q(table)}").fetchone()["c"]
        with conn:
            conn.execute(f"DROP TABLE {_q(table)}")
    finally:
        conn.close()
    return {"ok": True, "action": "drop-table", "table": table, "rowsDropped": row_count}


def drop_column(path: str, table: str, column: str) -> dict:
    """Drop a column, preserving every other column and every row.

    Uses native `ALTER TABLE ... DROP COLUMN` when the running SQLite
    supports it (3.35.0+); otherwise falls back to the standard SQLite
    recipe of recreating the table without that column inside a single
    transaction (rows, `_id` values and remaining columns untouched).
    """
    _check_ident(column, "column name")
    if column == ID_COLUMN:
        raise DbError(f'"{ID_COLUMN}" is the reserved primary key — it cannot be dropped')
    conn = connect(path)
    try:
        _require_table(conn, table)
        existing = _columns(conn, table)
        if column not in existing:
            raise DbError(f"column {column!r} not found in {table} — columns: {existing}")
        remaining = [c for c in existing if c != column]
        if len(remaining) <= 1:
            raise DbError(f"cannot drop {column!r}: {table} would be left with no data columns")
        with conn:
            try:
                conn.execute(f"ALTER TABLE {_q(table)} DROP COLUMN {_q(column)}")
            except sqlite3.OperationalError:
                # Older SQLite without DROP COLUMN support: recreate the
                # table without the column, copying every row across.
                tmp = f"{table}__drop_tmp"
                conn.execute(f"DROP TABLE IF EXISTS {_q(tmp)}")
                cols_sql = ", ".join(
                    f"{_q(ID_COLUMN)} INTEGER PRIMARY KEY AUTOINCREMENT" if c == ID_COLUMN
                    else f"{_q(c)} TEXT"
                    for c in remaining
                )
                conn.execute(f"CREATE TABLE {_q(tmp)} ({cols_sql})")
                col_list = ", ".join(_q(c) for c in remaining)
                conn.execute(
                    f"INSERT INTO {_q(tmp)} ({col_list}) SELECT {col_list} FROM {_q(table)}"
                )
                conn.execute(f"DROP TABLE {_q(table)}")
                conn.execute(f"ALTER TABLE {_q(tmp)} RENAME TO {_q(table)}")
            new_columns = _columns(conn, table)
            total = conn.execute(f"SELECT COUNT(*) AS c FROM {_q(table)}").fetchone()["c"]
    finally:
        conn.close()
    return {"ok": True, "action": "drop-column", "table": table,
            "droppedColumn": column, "columns": new_columns, "rows": total}


def import_csv(path: str, table: str, file: str, key: str | None = None) -> dict:
    if not os.path.isfile(file):
        raise DbError(f"file not found: {file}")
    with open(file, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames:
            raise DbError(f"empty CSV (no header row): {file}")
        rows = []
        for raw in reader:
            row = {k: v for k, v in raw.items()
                   if k and k != ID_COLUMN and not k.startswith("_")}
            if any((v or "").strip() for v in row.values()):
                rows.append(row)
    if not rows:
        raise DbError(f"no data rows in {file}")
    result = add(path, table, rows, key=key)
    result["action"] = "import-csv"
    result["file"] = file
    return result


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------

def _load_json(value: str, flag: str):
    if value == "-":
        value = sys.stdin.read()
    try:
        return json.loads(value)
    except json.JSONDecodeError as exc:
        raise DbError(f"{flag}: invalid JSON ({exc})") from None


def _parse_set(pairs: list[str]) -> dict:
    sets = {}
    for pair in pairs:
        if "=" not in pair:
            raise DbError(f"--set expects col=value, got {pair!r}")
        col, value = pair.split("=", 1)
        sets[col.strip()] = value
    return sets


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(
        description="Single door to a Bricks workspace database (JSON in, JSON out)."
    )
    parser.add_argument("--root", default="bricks",
                        help="Bricks data root used to resolve the current workspace")
    parser.add_argument("--db", default=None,
                        help="explicit path to a bricks.db (bypasses workspace resolution)")
    sub = parser.add_subparsers(dest="command", required=True)

    # `--db` / `--root` are global (declared on the top parser above), but a
    # bare argparse subparser rejects them AFTER the subcommand — so
    # `db.py add companies --rows … --db /path` fails while
    # `db.py --db /path add companies …` works. The model reliably writes
    # --db last (field-tested friction), so accept it in BOTH positions:
    # every subparser inherits this flag group. Defaults are SUPPRESSED so
    # that omitting the flag after the subcommand never clobbers a value
    # given before it (the top-parser default already covers that case).
    dbflags = argparse.ArgumentParser(add_help=False)
    dbflags.add_argument("--root", default=argparse.SUPPRESS,
                         help="Bricks data root (also accepted before the subcommand)")
    dbflags.add_argument("--db", default=argparse.SUPPRESS,
                         help="explicit bricks.db path (also accepted before the subcommand)")

    def add_cmd(name, **kw):
        return sub.add_parser(name, parents=[dbflags], **kw)

    add_cmd("init", help="create the database file if missing (WAL mode)")
    add_cmd("tables", help="list tables with row counts and columns")

    p = add_cmd("schema", help="show a table's columns")
    p.add_argument("table")

    p = add_cmd("select", help="read rows (JSON objects)")
    p.add_argument("table")
    p.add_argument("--where", default=None, help="SQL condition, e.g. \"status='pending'\"")
    p.add_argument("--cols", default=None, help="comma-separated column names")
    p.add_argument("--limit", type=int, default=None,
                   help=f"max rows (default {DEFAULT_SELECT_LIMIT}; -1 = no limit)")
    p.add_argument("--offset", type=int, default=0)
    p.add_argument("--order", default=None, help="ORDER BY clause, e.g. \"name ASC\"")

    p = add_cmd("count", help="count rows")
    p.add_argument("table")
    p.add_argument("--where", default=None)

    p = add_cmd("claim", help="atomically select pending rows and mark them running")
    p.add_argument("table")
    p.add_argument("status_col", help="the X_status column to claim on")
    p.add_argument("--limit", type=int, default=25, help="max rows to claim (default 25)")
    p.add_argument("--cols", default=None, help="columns to return (always includes _id)")
    p.add_argument("--where", default=None, help="extra SQL condition ANDed to the claim")
    p.add_argument("--retry-failed", action="store_true",
                   help="also claim 'failed' rows (explicit retry)")

    p = add_cmd("add", help="insert rows; creates table/columns as needed")
    p.add_argument("table")
    p.add_argument("--rows", required=True, help="JSON list of objects, or '-' for stdin")
    p.add_argument("--key", default=None,
                   help="dedup column: rows whose key value already exists are skipped")

    p = add_cmd("modify", help="update cells by _id, or bulk --set with --where")
    p.add_argument("table")
    p.add_argument("--updates", default=None,
                   help='JSON list of objects with an "_id" key, or \'-\' for stdin')
    p.add_argument("--set", action="append", default=[], metavar="COL=VALUE",
                   help="bulk assignment (repeatable), requires --where")
    p.add_argument("--where", default=None)

    p = add_cmd("remove", help="delete rows by _id list or by --where")
    p.add_argument("table")
    p.add_argument("--ids", default=None, help="JSON list of _id values, or '-' for stdin")
    p.add_argument("--where", default=None)

    p = add_cmd("drop-table", help="permanently delete a table and all its rows")
    p.add_argument("table")
    p.add_argument("--confirm", action="store_true",
                   help="required acknowledgement — this cannot be undone")

    p = add_cmd("drop-column", help="drop one column, preserving all other columns and rows")
    p.add_argument("table")
    p.add_argument("column")

    p = add_cmd("import-csv", help="import a CSV file into a table")
    p.add_argument("table")
    p.add_argument("file")
    p.add_argument("--key", default=None, help="dedup column (same as add --key)")

    args = parser.parse_args(argv)
    try:
        path = resolve_db_path(args.root, args.db)
        if args.command == "init":
            result = init(path)
        elif args.command == "tables":
            result = tables(path)
        elif args.command == "schema":
            result = schema(path, args.table)
        elif args.command == "select":
            result = select(path, args.table, args.where, args.cols,
                            args.limit, args.offset, args.order)
        elif args.command == "count":
            result = count(path, args.table, args.where)
        elif args.command == "claim":
            result = claim(path, args.table, args.status_col, args.limit,
                           args.cols, args.where, args.retry_failed)
        elif args.command == "add":
            result = add(path, args.table, _load_json(args.rows, "--rows"), args.key)
        elif args.command == "modify":
            updates = _load_json(args.updates, "--updates") if args.updates else None
            sets = _parse_set(getattr(args, "set")) if getattr(args, "set") else None
            result = modify(path, args.table, updates, sets, args.where)
        elif args.command == "remove":
            ids = _load_json(args.ids, "--ids") if args.ids else None
            result = remove(path, args.table, ids, args.where)
        elif args.command == "drop-table":
            if not args.confirm:
                raise DbError("drop-table requires --confirm (this permanently deletes the table)")
            result = drop_table(path, args.table)
        elif args.command == "drop-column":
            result = drop_column(path, args.table, args.column)
        else:
            result = import_csv(path, args.table, args.file, args.key)
    except DbError as exc:
        print(json.dumps({"ok": False, "error": str(exc)}, ensure_ascii=False),
              file=sys.stderr)
        return 1

    print(json.dumps(result, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    sys.exit(main())
